server:
  # 应用端口
  port: 8081
  # tomcat 配置
  tomcat:
    max-threads: 200 # 最大线程数量 默认200
    uri-encoding: UTF-8
    max-connections: 1000 # 最大连接数量 1000
    min-spare-threads: 20 # 初始化线程是20

spring:
  freemarker:
    suffix: .ftl
    cache: false
  # 静态资源引用
  mvc:
    static-path-pattern: /static/**

websocketPath: /ws
